/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Darwin w134-87-133-244.wireless.uvic.ca 15.2.0 x86_64"
#define LGL_COMPILED "Fri Jul 29 16:28:50 PDT 2016"
#define LGL_RELEASED "Thu Jul  7 10:21:35 CEST 2016"
#define LGL_VERSION "bbc"
#define LGL_ID "923038088b727dcc8bd03aa8dfb5013bd03bf8c4"
